# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist

# Setup
title:            Ganesh Palanikumar
tagline:          'Software Builder'
description:      ''
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Ganesh Palanikumar'
  email:          'ganeshpkumar93@gmail.com'
  # url:            https://twitter.com/ganeshpalanikumar

paginate:         5

# Custom vars
version:          0.0.2

github:
  repo:           https://github.com/ganesh-palanikumar/ganesh-palanikumar.github.io
  
